// themes/spa/src/components/Layout.vue
<template>
  <div class="p-6 max-w-sm">xx</div>

  <h1>sss</h1>

  <header class="header" itemscope itemtype="http://schema.org/WPHeader">
    <div class="header-inner">
      <!-- {% include '_partials/header/index.swig' %} -->
    </div>
  </header>

  <main class="main">
    <div class="main-inner">
      <slot></slot>
    </div>
  </main>

  <footer class="footer">
    <div class="footer-inner">
      <!-- {% include '_partials/languages.swig' %} -->
    </div>
  </footer>
</template>

<script lang="ts">
export default {
  name: 'Layout',
};
</script>

<script lang="ts" setup></script>

// themes/svelte/layout/_components/Layout.svelte
<svelte:head>
  <Analytics />
</svelte:head>

<div>
  <div class="headband" />

  <header
    id="header"
    class="header"
    itemscope
    itemtype="http://schema.org/WPHeader"
  >
    <div class="header-inner">
      <slot name="header" />
    </div>
  </header>

  <main id="main" class="main">
    <div class="main-inner">
      <div class="content-wrap">
        <div id="content" class="content">
          <slot />
        </div>
        <!-- {% include '_third-party/duoshuo-hot-articles.swig' %} -->
        <!-- {% include '_partials/comments.swig' %} -->
      </div>
      <!-- {% block sidebar %}{% endblock %} -->
    </div>
  </main>
</div>

<script lang="ts">
  import Analytics from './Analytics/index.svelte';
</script>
