// themes/spa/src/components/LoadGlobalData.vue
<template>
  <div>xx - {{ resp.loading }} - {{ xs }}</div>
</template>

<script lang="ts">
import { useAxios } from '@/hooks/useAxios';
import { computed, defineComponent } from 'vue';
import { useRouter } from 'vue-router';
import { toBase64, formatHtmlPath } from '@shared';
import { useStore } from 'vuex';

let isPreRender = true;

export default defineComponent({
  name: 'LoadGlobalData',
  setup() {
    const router = useRouter();
    const [resp, fetchPageData, { cancel }] = useAxios('');
    const store = useStore();

    router.afterEach((to, from) => {
      if (__SSR__ || to.path === from.path || isPreRender) {
        isPreRender = false;
        return;
      }

      cancel();
      fetchPageData({
        url: '/json/' + toBase64(formatHtmlPath(to.path)) + '.json',
      }).then(resp => {
        store.commit('global/setPageData', resp.data || {});
      });
    });

    return {
      resp,
      xs: computed(() => JSON.stringify(resp.value.data)),
    };
  },
});
</script>

// themes/svelte/layout/_components/LoadGlobalData.svelte
<div>
  ddd: {$gLoading} - {$resp.callTimes}
</div>

<script context="module">
  let skipFirstFlag = true;
</script>

<script lang="ts">
  import { useAxios } from '@/hooks/useAxios';
  import { gLoading, gStore } from '@/store/global';
  import { useLocation } from 'svelte-navigator';
  import { toBase64, formatHtmlPath } from '@shared';

  const loc = useLocation();
  $: pathname = $loc.pathname;
  const [resp, fetchPageData, { cancel }] = useAxios('');

  $: {
    $gLoading = $resp.loading;
  }

  $: if (!__SSR__ && pathname) {
    if (!skipFirstFlag) {
      cancel();
      $gStore.page = {};
      fetchPageData({
        url: '/json/' + toBase64(formatHtmlPath(pathname)) + '.json',
      }).then(resp => {
        $gStore = resp.data || {};
      });
    }
    skipFirstFlag = false;
  }
</script>
